name: news_api
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.8.13
  - setuptools=63.4.1
  - sqlite=3.39.2
  - wheel=0.37.1
  - pip:
    - anyio==3.6.1
    - astroid==2.12.10
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - black==22.8.0
    - brotli==1.0.9
    - cffi==1.15.1
    - cfgv==3.3.1
    - charset-normalizer==2.1.1
    - colorama==0.4.5
    - configargparse==1.5.3
    - coverage==6.4.4
    - cssselect==1.1.0
    - distlib==0.3.6
    - fastapi==0.85.0
    - feedfinder2==0.0.4
    - feedparser==6.0.10
    - filelock==3.8.0
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - gevent==21.12.0
    - geventhttpclient==2.0.2
    - greenlet==1.1.3
    - h11==0.13.0
    - identify==2.5.5
    - idna==3.4
    - importlib-metadata==4.12.0
    - iniconfig==1.1.1
    - isort==5.10.1
    - itsdangerous==2.1.2
    - jieba3k==0.35.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - lazy-object-proxy==1.7.1
    - locust==2.12.1
    - lxml==4.9.1
    - markupsafe==2.1.1
    - mccabe==0.7.0
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - newsapi-python==0.2.6
    - newspaper3k==0.2.8
    - nodeenv==1.7.0
    - numpy==1.23.3
    - packaging==21.3
    - pandas==1.5.0
    - pathspec==0.10.1
    - pillow==9.2.0
    - platformdirs==2.5.2
    - pre-commit==2.20.0
    - pycparser==2.21
    - pydantic==1.10.2
    - pylint==2.15.3
    - pyparsing==3.0.9
    - pytest==7.1.3
    - pytest-cov==3.0.0
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - regex==2022.9.13
    - requests==2.28.1
    - requests-file==1.5.1
    - roundrobin==0.0.4
    - sgmllib3k==1.0.0
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - starlette==0.20.4
    - tinysegmenter==0.3
    - tldextract==3.3.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.4
    - tqdm==4.64.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - uvicorn==0.18.3
    - virtualenv==20.16.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.8.1
    - zope-event==4.5.0
    - zope-interface==5.4.0
